after_failure:
- adb logcat -d
android:
  components:
  - android-21
  - android-19
  - sys-img-armeabi-v7a-android-21
  - build-tools-21.0.1
before_install:
- android list targets
- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
- emulator -avd test -no-skin -no-audio -no-window &
before_script:
- adb devices
- ./wait_for_emulator
branches:
  only:
  - master
  - release
  - fast-test
env:
  matrix:
  - ANDROID_TARGET=android-10  ANDROID_ABI=armeabi
  - ANDROID_TARGET=android-15  ANDROID_ABI=armeabi-v7a
  - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dfindbugs.skip=true -Dcheckstyle.skip=true -Dpmd.skip=true -Dandroid.generateApk=false
language: android
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script: mvn install -Dandroid.device=test -Dmaven.javadoc.skip=true -Dandroid.dex.optimize=false
